// Vendor the webfonts the design vocabulary can choose from.
//
//   node scripts/fonts.mjs            # fetch anything missing, rewrite fonts.css
//   node scripts/fonts.mjs --force    # re-fetch everything
//
// Why self-hosted rather than a stylesheet link: a client site makes zero external
// requests, which is what lets it ship without a cookie banner. Google Fonts' CSS
// endpoint is a request to Google from the visitor's browser, and their own guidance
// no longer claims otherwise -- a German court has already ruled the embed transfers
// an IP address without consent. Self-hosted woff2 keeps the guarantee intact and is
// faster besides (no second connection before the first paint).
//
// All three families are SIL Open Font License 1.1, so redistributing the woff2 inside
// a client's deploy is allowed. FAMILIES below is the list that OFL covers; adding a
// family means checking its licence first, not just adding a line.
//
// Only latin + latin-ext are kept. The unicode-range on each face means latin-ext stays
// off the wire until an accented character actually needs it, which for Dutch copy is
// rare -- so the common case is one file per weight.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const APP_ROOT = fileURLToPath(new URL('..', import.meta.url))
const FONTS_DIR = path.join(APP_ROOT, 'fonts')
const CSS_OUT = path.join(APP_ROOT, 'src', 'styles', 'fonts.css')

// Chrome UA: the CSS2 endpoint serves woff2 only to browsers that support it, and
// answers a bare curl with truetype.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

/**
 * key      directory under fonts/ and the filename prefix
 * family   the CSS font-family name Google serves it under
 * weights  only what a face actually uses; every extra weight is a file a client ships
 */
const FAMILIES = [
  { key: 'figtree', family: 'Figtree', weights: [400, 500, 700] },
  { key: 'archivo', family: 'Archivo', weights: [600, 700] },
  { key: 'instrumentserif', family: 'Instrument Serif', weights: [400] },
]

const SUBSETS = new Set(['latin', 'latin-ext'])

const force = process.argv.includes('--force')

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`)
  return res.text()
}

/** Split Google's CSS into { subset, weight, url, unicodeRange } records. */
function parseFaces(css) {
  const faces = []
  // Each face is preceded by a /* subset */ comment; that comment is the only place
  // the subset name appears, so the split has to keep it.
  const chunks = css.split(/\/\*\s*([a-z0-9-]+)\s*\*\//i).slice(1)
  for (let i = 0; i < chunks.length; i += 2) {
    const subset = chunks[i]
    const block = chunks[i + 1] ?? ''
    if (!SUBSETS.has(subset)) continue
    // Italics are never used by the vocabulary (the marketing voice rules ban italic on
    // Dutch B2B copy), so they are not downloaded.
    if (/font-style:\s*italic/.test(block)) continue
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1]
    const url = block.match(/src:\s*url\(([^)]+)\)/)?.[1]
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
    if (weight && url && range) faces.push({ subset, weight: Number(weight), url, range })
  }
  return faces
}

const rules = []
let fetched = 0
let kept = 0

for (const { key, family, weights } of FAMILIES) {
  const dir = path.join(FONTS_DIR, key)
  fs.mkdirSync(dir, { recursive: true })
  const spec = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weights.join(';')}&display=swap`
  const faces = parseFaces(await fetchText(spec))

  for (const weight of weights) {
    const forWeight = faces.filter((f) => f.weight === weight)
    if (forWeight.length === 0) throw new Error(`${family} ${weight}: Google served no face`)
    for (const face of forWeight) {
      const name = `${key}-${weight}-${face.subset.replace('-', '')}.woff2`
      const file = path.join(dir, name)
      if (force || !fs.existsSync(file)) {
        const res = await fetch(face.url, { headers: { 'User-Agent': UA } })
        if (!res.ok) throw new Error(`GET ${face.url} -> ${res.status}`)
        fs.writeFileSync(file, Buffer.from(await res.arrayBuffer()))
        fetched++
      } else {
        kept++
      }
      rules.push(
        `@font-face {\n` +
          `  font-family: '${family}';\n` +
          `  font-style: normal;\n` +
          `  font-weight: ${weight};\n` +
          `  font-display: swap;\n` +
          `  src: url('/fonts/${name}') format('woff2');\n` +
          `  unicode-range: ${face.range};\n` +
          `}`,
      )
    }
  }
}

const header = `/* GENERATED by scripts/fonts.mjs -- do not edit by hand.
 *
 * Self-hosted so a client site makes zero external requests, which is what lets it
 * ship without a cookie banner. All families are SIL OFL 1.1 (redistributable).
 * Which face a site actually uses is set by stijl.letterontwerp; the other @font-face
 * rules cost a few bytes of CSS and are never requested, because nothing names them.
 *
 * Files are copied into dist/fonts/ per client by the fonts mount in astro.config.mjs,
 * and only for the family that client's skin selected.
 */\n\n`

fs.writeFileSync(CSS_OUT, header + rules.join('\n\n') + '\n')
console.log(
  `[fonts] ${FAMILIES.length} families, ${rules.length} faces ` +
    `(${fetched} downloaded, ${kept} already present)\n[fonts] wrote ${path.relative(APP_ROOT, CSS_OUT)}`,
)
